Update cmake.yml

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -42,5 +42,26 @@ jobs:
       working-directory: ${{github.workspace}}/Example/build
       shell: bash
       # Execute the just built executable
-      run: ./Example || echo 0
-        
+      run: ./Example || echo "Fails as expected"
+      
+    - name: Configure CMake (Release)
+      # Use a bash shell so we can use the same syntax for environment variable
+      # access regardless of the host operating system
+      shell: bash
+      working-directory: ${{github.workspace}}/Example/build
+      # Note the current convention is to use the -S and -B options here to specify source
+      # and build directories, but this is only available with CMake 3.13 and higher.
+      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
+      run: cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
+
+    - name: Build (Release)
+      working-directory: ${{github.workspace}}/Example/build
+      shell: bash
+      # Execute the build.  You can specify a specific target with "--target <NAME>"
+      run: cmake --build .
+      
+    - name: Execute (Release)
+      working-directory: ${{github.workspace}}/Example/build
+      shell: bash
+      # Execute the just built executable
+      run: ./Example
