Updated Github Workflow

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -2,10 +2,6 @@ name: CMake Build
 
 on: [push]
 
-env:
-  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
-  BUILD_TYPE: Release
-
 jobs:
   build:
     # The CMake configure and build commands are platform agnostic and should work equally
@@ -13,55 +9,28 @@ jobs:
     # cross-platform coverage.
     # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: ${{github.workspace}}/Example
+        shell: bash
 
     steps:
-    - uses: actions/checkout@v2
-
-    - name: Create Build Environment
-      # Some projects don't allow in-source building, so create a separate build directory
-      # We'll use this as our working directory for all subsequent commands
-      run: cmake -E make_directory ${{github.workspace}}/Example/build
+    - uses: actions/checkout@v3
 
     - name: Configure CMake (Debug)
-      # Use a bash shell so we can use the same syntax for environment variable
-      # access regardless of the host operating system
-      shell: bash
-      working-directory: ${{github.workspace}}/Example/build
-      # Note the current convention is to use the -S and -B options here to specify source
-      # and build directories, but this is only available with CMake 3.13 and higher.
-      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
-      run: cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug
+      run: cmake . -G"Unix Makefiles" -B"build" -DCMAKE_BUILD_TYPE=Debug
 
     - name: Build (Debug)
-      working-directory: ${{github.workspace}}/Example/build
-      shell: bash
-      # Execute the build.  You can specify a specific target with "--target <NAME>"
-      run: cmake --build .
+      run: cmake --build build
 
     - name: Execute (Debug)
-      working-directory: ${{github.workspace}}/Example/build
-      shell: bash
-      # Execute the just built executable
-      run: ./Example || echo "Fails as expected"
+      run: '(./build/Example || ([[ `./build/Example | tail -n1` == "Assertion failed: "* ]] && echo "Fails as expected")) || false'
 
     - name: Configure CMake (Release)
-      # Use a bash shell so we can use the same syntax for environment variable
-      # access regardless of the host operating system
-      shell: bash
-      working-directory: ${{github.workspace}}/Example/build
-      # Note the current convention is to use the -S and -B options here to specify source
-      # and build directories, but this is only available with CMake 3.13 and higher.
-      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
-      run: cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
+      run: cmake . -G"Unix Makefiles" -B"build" -DCMAKE_BUILD_TYPE=Release
 
     - name: Build (Release)
-      working-directory: ${{github.workspace}}/Example/build
-      shell: bash
-      # Execute the build.  You can specify a specific target with "--target <NAME>"
-      run: cmake --build .
+      run: cmake --build build
 
     - name: Execute (Release)
-      working-directory: ${{github.workspace}}/Example/build
-      shell: bash
-      # Execute the just built executable
-      run: ./Example
+      run: ./build/Example
